// import {
//   DashboardPath,
//   ConnectionsPath,
//   ConversationsPath,
//   JobsPath,
//   JobBoardPath,
//   SchedulePath,
//   VirtualFairPath,
//   CandidatesPath,
//   SettingsPath,
//   HelpPath,
//   InsightPath,
//   PipelinePath,
//   AssessmentsPath,
//   TalentPoolPath,
//   SavedBookmark,
// } from "@layout/sidebar/svgIcon/paths";
// const isProd = process.env.NEXT_PUBLIC_NODE_ENV === "production";
// const showEmailCampaign = !isProd;
const routes = {
  //   emailVerify: {
  //     route: "/emailVerification",
  //     name: "Email Verify",
  //     viewable: {},
  //   },
  //   home: { route: "/", name: "Home", viewable: {} },
  //   login: { route: "/onboarding/login", name: "Login", viewable: {} },
  dashboard: {
    route: "/dashboard",
    name: "Dashboard",
    category: "general",
    // Icon: DashboardPath,
    viewable: { candidates: true, employers: true },
    sidebarOpen: true,
  },
  upcomingEvents: {
    route: "/dashboard/upcoming-events",
    name: "Upcoming Events",
    category: "general",
    // Icon: DashboardPath,
    viewable: { candidates: true, employers: true },
    sidebarOpen: true,
  },
  verseForToday: {
    route: "/dashboard/verse-for-today",
    name: "Daily Verses",
    category: "general",
    // Icon: DashboardPath,
    viewable: { candidates: true, employers: true },
    sidebarOpen: true,
  },
  bibleStudy: {
    route: "/dashboard/bible-study",
    name: "Bible Study",
    category: "general",
    // Icon: DashboardPath,
    viewable: { candidates: true, employers: true },
    sidebarOpen: true,
  },
  users: {
    route: "/dashboard/users",
    name: "Users",
    category: "general",
    // Icon: DashboardPath,
    viewable: { candidates: true, employers: true },
    sidebarOpen: true,
  },
  feedback: {
    route: "/dashboard/feedbacks",
    name: "Feedbacks",
    category: "general",
    // Icon: DashboardPath,
    viewable: { candidates: true, employers: true },
    sidebarOpen: true,
  },
  //   jobs: {
  //     route: "/dashboard/jobs",
  //     name: "Jobs",
  //     category: "general",
  //     // Icon: JobsPath,
  //     viewable: { candidates: false, employers: true },
  //     sidebarOpen: true,
  //   },
  //   jobBoard: {
  //     route: "/dashboard/job-board",
  //     name: "Jobs",
  //     category: "general",
  //     // Icon: JobBoardPath,
  //     viewable: { candidates: true, employers: false },
  //     sidebarOpen: false,
  //   },
  //   applications: {
  //     route: "/dashboard/applications",
  //     name: "Applications",
  //     category: "general",
  //     // Icon: JobsPath,
  //     viewable: { candidates: true, employers: false },
  //     sidebarOpen: true,
  //   },
  //   conversations: {
  //     route: "/dashboard/conversations",
  //     name: "Conversations",
  //     category: "general",
  //     // Icon: ConversationsPath,
  //     viewable: { candidates: true, employers: true },
  //     sidebarOpen: false,
  //   },
  //   Candidates: {
  //     route: "/dashboard/candidates",
  //     name: "Find Talent",
  //     category: "general",
  //     // Icon: CandidatesPath,
  //     viewable: { employers: true },
  //     sidebarOpen: false,
  //   },
  //   connections: {
  //     route: "/dashboard/connections",
  //     name: "Connections",
  //     category: "general",
  //     // Icon: ConnectionsPath,
  //     viewable: { candidates: true, employers: false },
  //     sidebarOpen: true,
  //   },

  //   assessments: {
  //     route: "/dashboard/assessments",
  //     name: "Assessments",
  //     category: "general",
  //     // Icon: AssessmentsPath,
  //     viewable: { candidates: true, employers: false },
  //     sidebarOpen: true,
  //   },

  //   pipeline: {
  //     route: "/dashboard/pipeline",
  //     name: "Pipeline",
  //     category: "general",
  //     // Icon: PipelinePath,
  //     viewable: { employers: true },
  //     sidebarOpen: true,
  //   },
  //   sourcing: {
  //     route: "/dashboard/sourcing",
  //     name: "Sourcing",
  //     category: "general",
  //     subRoutes: [
  //       // {
  //       //   route: "/dashboard/sourcing/job-blast",
  //       //   name: "Job Blast",
  //       // },
  //       {
  //         route: "/dashboard/sourcing/interview-fair",
  //         name: "Interview Fair",
  //         show: true,
  //         sidebarOpen: true,
  //       },
  //       {
  //         route: "/dashboard/sourcing/loubby-card",
  //         name: "Loubby Cards",
  //         show: true,
  //         sidebarOpen: true,
  //       },
  //       {
  //         route: "/dashboard/sourcing/email-campaign",
  //         name: "Email Campaign",
  //         // show: showEmailCampaign,
  //         sidebarOpen: true,
  //       },
  //     ],
  //     // Icon: VirtualFairPath,
  //     viewable: { candidates: false, employers: true },
  //   },
  //   schedule: {
  //     route: "/dashboard/schedule",
  //     name: "Schedule",
  //     category: "general",
  //     // Icon: SchedulePath,
  //     viewable: { candidates: true, employers: true },
  //     sidebarOpen: true,
  //   },

  //   TalentPool: {
  //     route: "/dashboard/talent-pool",
  //     name: "Talent Pool",
  //     category: "general",
  //     // Icon: TalentPoolPath,
  //     viewable: { employers: true, candidates: false },
  //     sidebarOpen: true,
  //   },
  //   settings: {
  //     route: "/dashboard/settings",
  //     name: "Settings",
  //     category: "support",
  //     // Icon: SettingsPath,
  //     viewable: { candidates: true, employers: true },
  //     sidebarOpen: false,
  //   },
  //   insights: {
  //     route: "/dashboard/insights",
  //     name: "Insights",
  //     category: "general",
  //     // Icon: InsightPath,
  //     viewable: { candidates: false, employers: true },
  //     sidebarOpen: true,
  //   },
  //   helpCenter: {
  //     route: "/dashboard/feedback",
  //     name: "Feedback",
  //     category: "support",
  //     // Icon: HelpPath,
  //     viewable: { candidates: true, employers: true },
  //     sidebarOpen: true,
  //   },
  //   profile: {
  //     route: "/dashboard/profile",
  //     name: "Profile",
  //     category: "profile",
  //     viewable: { candidates: true, employers: true },
  //     sidebarOpen: true,
  //   },
  //   virtualFair: {
  //     route: "/dashboard/virtual-fair",
  //     name: "Virtual Fair",
  //     category: "general",
  //     // Icon: VirtualFairPath,
  //     viewable: { candidates: true, employers: false },
  //     sidebarOpen: true,
  //   },
  //   Saved: {
  //     route: "/dashboard/saved",
  //     name: "Saved",
  //     category: "general",
  //     // Icon: SavedBookmark,
  //     viewable: { candidates: true, employers: true },
  //     sidebarOpen: true,
  //   },
};

export default routes;

////FiInbox
////BsBell
