import { players, soccer_team, team } from "./players";

export const jan25 = [
  {
    home: team.ayo,
    homeGoals: 3,
    homeTeam: soccer_team.manU,
    away: team.chuks,
    awayGoals: 2,
    awayTeam: soccer_team.manCity,
  },
  {
    home: team.presido,
    homeGoals: 0,
    away: team.piso,
    awayGoals: 5,
    homeTeam: soccer_team.liverpool,
    awayTeam: soccer_team.england,
  },
  {
    home: team.presido,
    homeGoals: 1,
    away: team.ayo,
    awayGoals: 5,
    homeTeam: soccer_team.liverpool,
    awayTeam: soccer_team.manU,
  },
  {
    home: team.piso,
    homeGoals: 5,
    away: team.chuks,
    awayGoals: 4,
    homeTeam: soccer_team.england,
    awayTeam: soccer_team.manCity,
  },
  {
    home: team.ayo,
    homeGoals: 3,
    away: team.piso,
    awayGoals: 3,
    homeTeam: soccer_team.manU,
    awayTeam: soccer_team.england,
  },
  {
    home: team.chuks,
    homeGoals: 5,
    away: team.presido,
    awayGoals: 2,
    homeTeam: soccer_team.manCity,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.ayo,
    homeGoals: 10,
    away: team.presido,
    awayGoals: 3,
    homeTeam: soccer_team.manU,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.chuks,
    homeGoals: 6,
    away: team.piso,
    awayGoals: 4,
    homeTeam: soccer_team.manCity,
    awayTeam: soccer_team.england,
  },
  {
    home: team.chuks,
    homeGoals: 8,
    away: team.ayo,
    awayGoals: 2,
    homeTeam: soccer_team.manCity,
    awayTeam: soccer_team.manU,
  },
  {
    home: team.piso,
    homeGoals: 6,
    away: team.presido,
    awayGoals: 2,
    homeTeam: soccer_team.england,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.piso,
    homeGoals: 6,
    away: team.ayo,
    awayGoals: 4,
    homeTeam: soccer_team.england,
    awayTeam: soccer_team.manU,
  },
  {
    home: team.chuks,
    homeGoals: 10,
    away: team.presido,
    awayGoals: 0,
    homeTeam: soccer_team.manCity,
    awayTeam: soccer_team.liverpool,
  },
];

export const feb25 = [
  {
    home: team.ayo,
    homeGoals: 0,
    homeTeam: soccer_team.manU,
    away: team.piso,
    awayGoals: 2,
    awayTeam: soccer_team.tottenham,
  },
  {
    home: team.chuks,
    homeGoals: 7,
    homeTeam: soccer_team.manCity,
    away: team.presido,
    awayGoals: 1,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.chuks,
    homeGoals: 1,
    homeTeam: soccer_team.manCity,
    away: team.ayo,
    awayGoals: 4,
    awayTeam: soccer_team.manU,
  },
  {
    home: team.presido,
    homeGoals: 0,
    homeTeam: soccer_team.liverpool,
    away: team.piso,
    awayGoals: 3,
    awayTeam: soccer_team.tottenham,
  },
  {
    home: team.ayo,
    homeGoals: 4,
    homeTeam: soccer_team.manU,
    away: team.presido,
    awayGoals: 3,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.piso,
    homeGoals: 4,
    homeTeam: soccer_team.tottenham,
    away: team.chuks,
    awayGoals: 2,
    awayTeam: soccer_team.manCity,
  },
  {
    home: team.piso,
    homeGoals: 3,
    homeTeam: soccer_team.tottenham,
    away: team.ayo,
    awayGoals: 4,
    awayTeam: soccer_team.manU,
  },
  {
    home: team.presido,
    homeGoals: 3,
    homeTeam: soccer_team.liverpool,
    away: team.chuks,
    awayGoals: 6,
    awayTeam: soccer_team.manCity,
  },
  {
    home: team.presido,
    homeGoals: 2,
    homeTeam: soccer_team.liverpool,
    away: team.ayo,
    awayGoals: 3,
    awayTeam: soccer_team.manU,
  },
  {
    home: team.chuks,
    homeGoals: 4,
    homeTeam: soccer_team.manCity,
    away: team.piso,
    awayGoals: 3,
    awayTeam: soccer_team.tottenham,
  },
  {
    home: team.ayo,
    homeGoals: 3,
    homeTeam: soccer_team.manU,
    away: team.chuks,
    awayGoals: 3,
    awayTeam: soccer_team.manCity,
  },
  {
    home: team.piso,
    homeGoals: 7,
    homeTeam: soccer_team.tottenham,
    away: team.presido,
    awayGoals: 0,
    awayTeam: soccer_team.liverpool,
  },
];

export const mar25 = [
  {
    home: team.presido,
    homeGoals: 0,
    homeTeam: soccer_team.liverpool,
    away: team.ayo,
    awayGoals: 7,
    awayTeam: soccer_team.psg,
  },
  {
    home: team.piso,
    homeGoals: 1,
    homeTeam: soccer_team.tottenham,
    away: team.chuks,
    awayGoals: 1,
    awayTeam: soccer_team.bayern,
  },
  {
    home: team.piso,
    homeGoals: 8,
    homeTeam: soccer_team.tottenham,
    away: team.presido,
    awayGoals: 1,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.chuks,
    homeGoals: 4,
    homeTeam: soccer_team.bayern,
    away: team.ayo,
    awayGoals: 5,
    awayTeam: soccer_team.psg,
  },
  {
    home: team.presido,
    homeGoals: 4,
    homeTeam: soccer_team.liverpool,
    away: team.chuks,
    awayGoals: 7,
    awayTeam: soccer_team.bayern,
  },
  {
    home: team.ayo,
    homeGoals: 4,
    homeTeam: soccer_team.psg,
    away: team.piso,
    awayGoals: 2,
    awayTeam: soccer_team.tottenham,
  },
  {
    home: team.ayo,
    homeGoals: 6,
    homeTeam: soccer_team.psg,
    away: team.presido,
    awayGoals: 1,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.chuks,
    homeGoals: 3,
    homeTeam: soccer_team.bayern,
    away: team.piso,
    awayGoals: 7,
    awayTeam: soccer_team.tottenham,
  },
  {
    home: team.chuks,
    homeGoals: 4,
    homeTeam: soccer_team.bayern,
    away: team.presido,
    awayGoals: 2,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.piso,
    homeGoals: 3,
    homeTeam: soccer_team.tottenham,
    away: team.ayo,
    awayGoals: 2,
    awayTeam: soccer_team.psg,
  },
  {
    home: team.presido,
    homeGoals: 0,
    homeTeam: soccer_team.liverpool,
    away: team.piso,
    awayGoals: 5,
    awayTeam: soccer_team.tottenham,
  },
  {
    home: team.ayo,
    homeGoals: 6,
    homeTeam: soccer_team.psg,
    away: team.chuks,
    awayGoals: 1,
    awayTeam: soccer_team.bayern,
  },
];

export const apr25 = [
  {
    home: team.ayo,
    homeGoals: 3,
    homeTeam: soccer_team.france,
    away: team.piso,
    awayGoals: 1,
    awayTeam: soccer_team.bayern,
  },
  {
    home: team.chuks,
    homeGoals: 5,
    homeTeam: soccer_team.manCity,
    away: team.presido,
    awayGoals: 2,
    awayTeam: soccer_team.real_madrid,
  },
  {
    home: team.chuks,
    homeGoals: 4,
    homeTeam: soccer_team.manCity,
    away: team.ayo,
    awayGoals: 4,
    awayTeam: soccer_team.france,
  },
  {
    home: team.presido,
    homeGoals: 1,
    homeTeam: soccer_team.real_madrid,
    away: team.piso,
    awayGoals: 4,
    awayTeam: soccer_team.bayern,
  },
  {
    home: team.ayo,
    homeGoals: 5,
    homeTeam: soccer_team.france,
    away: team.presido,
    awayGoals: 2,
    awayTeam: soccer_team.real_madrid,
  },
  {
    home: team.piso,
    homeGoals: 0,
    homeTeam: soccer_team.bayern,
    away: team.chuks,
    awayGoals: 3,
    awayTeam: soccer_team.manCity,
  },
  {
    home: team.ayo,
    homeGoals: 9,
    homeTeam: soccer_team.france,
    away: team.chuks,
    awayGoals: 3,
    awayTeam: soccer_team.manCity,
  },

  {
    home: team.piso,
    homeGoals: 1,
    homeTeam: soccer_team.bayern,
    away: team.presido,
    awayGoals: 8,
    awayTeam: soccer_team.real_madrid,
  },
  {
    home: team.piso,
    homeGoals: 1,
    homeTeam: soccer_team.bayern,
    away: team.ayo,
    awayGoals: 5,
    awayTeam: soccer_team.france,
  },
  {
    home: team.presido,
    homeGoals: 4,
    homeTeam: soccer_team.real_madrid,
    away: team.chuks,
    awayGoals: 3,
    awayTeam: soccer_team.manCity,
  },
  {
    home: team.presido,
    homeGoals: 2,
    homeTeam: soccer_team.real_madrid,
    away: team.ayo,
    awayGoals: 6,
    awayTeam: soccer_team.france,
  },
  {
    home: team.chuks,
    homeGoals: 2,
    homeTeam: soccer_team.manCity,
    away: team.piso,
    awayGoals: 5,
    awayTeam: soccer_team.bayern,
  },
];

export const apr25e = [
  // {
  //   home: team.ayo,
  //   homeGoals: 3,
  //   homeTeam: soccer_team.france,
  //   away: team.presido,
  //   awayGoals: 1,
  //   awayTeam: soccer_team.bayern,
  // },
];
