import { players, soccer_team, team } from "./players";

export const jan25 = [
  {
    home: team.ayo,
    homeGoals: 3,
    homeTeam: soccer_team.manU,
    away: team.chuks,
    awayGoals: 2,
    awayTeam: soccer_team.manCity,
  },
  {
    home: team.presido,
    homeGoals: 0,
    away: team.piso,
    awayGoals: 5,
    homeTeam: soccer_team.liverpool,
    awayTeam: soccer_team.england,
  },
  {
    home: team.presido,
    homeGoals: 1,
    away: team.ayo,
    awayGoals: 5,
    homeTeam: soccer_team.liverpool,
    awayTeam: soccer_team.manU,
  },
  {
    home: team.piso,
    homeGoals: 5,
    away: team.chuks,
    awayGoals: 4,
    homeTeam: soccer_team.england,
    awayTeam: soccer_team.manCity,
  },
  {
    home: team.ayo,
    homeGoals: 3,
    away: team.piso,
    awayGoals: 3,
    homeTeam: soccer_team.manU,
    awayTeam: soccer_team.england,
  },
  {
    home: team.chuks,
    homeGoals: 5,
    away: team.presido,
    awayGoals: 2,
    homeTeam: soccer_team.manCity,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.ayo,
    homeGoals: 10,
    away: team.presido,
    awayGoals: 3,
    homeTeam: soccer_team.manU,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.chuks,
    homeGoals: 6,
    away: team.piso,
    awayGoals: 4,
    homeTeam: soccer_team.manCity,
    awayTeam: soccer_team.england,
  },
  {
    home: team.chuks,
    homeGoals: 8,
    away: team.ayo,
    awayGoals: 2,
    homeTeam: soccer_team.manCity,
    awayTeam: soccer_team.manU,
  },
  {
    home: team.piso,
    homeGoals: 6,
    away: team.presido,
    awayGoals: 2,
    homeTeam: soccer_team.england,
    awayTeam: soccer_team.liverpool,
  },
  {
    home: team.piso,
    homeGoals: 6,
    away: team.ayo,
    awayGoals: 4,
    homeTeam: soccer_team.england,
    awayTeam: soccer_team.manU,
  },
  {
    home: team.chuks,
    homeGoals: 10,
    away: team.presido,
    awayGoals: 0,
    homeTeam: soccer_team.manCity,
    awayTeam: soccer_team.liverpool,
  },
];
